name: CI project 14
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Create Database & load Fixtures
        env:
          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/test_db'
        run: |           
          php bin/console doctrine:database:drop --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
          php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test

      - name: Run tests
        run: php bin/phpunit tests/

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src -l 6
